    const servers = [
        "n00dles",
        "  max-hardware",
        "foodnstuff",
        "sigma-cosmetics",
        "joesguns",
        "hong-fang-tea",
        "harakiri-sushi",
        "  zer0",
        "    silver-helix",
        "      rothman-uni",
        "      summit-uni",
        "      catalyst",
        "    phantasy",
//      "  CSEC",
        "    neo-net",
        "      johnson-ortho",
        "    omega-net",
        "      the-hub",
        "      comptek",
//      "        I.I.I.I",
        "      netlink",
        "iron-gym",
        "  nectar-net",
        "millenium-fitness",
        "rho-construction",
        "alpha-ent",
        "aevum-police"
       ]

       export { servers }